[openbox] changed to pacui - fix error in browsers menu

diff --git a/community/openbox/scripts/manjaro-browsers-pipemenu b/community/openbox/scripts/manjaro-browsers-pipemenu
--- a/community/openbox/scripts/manjaro-browsers-pipemenu
+++ b/community/openbox/scripts/manjaro-browsers-pipemenu
@@ -13,12 +13,12 @@ FAIL_MSG="No Apps Installed"
 CMD=(chromium chromium-snapshot-bin firefox firefox-developer-edition
      google-chrome-stable opera qutebrowser vivaldi vivaldi-snapshot
      )
-DESC=(Chromium "Chromium Snapshot" Firefox "Firefox-Dev"
-      "Google Chrome" Opera qutebrowser Vivaldi "Vivaldi-Snapshot"
+DESC=("Chromium" "Chromium Snapshot" "Firefox" "Firefox-Dev"
+      "Google Chrome" "Opera qutebrowser" "Vivaldi" "Vivaldi-Snapshot"
       )
 
-if ! . "/usr/lib/manjaro/common/al-include.cfg" 2>/dev/null; then
-    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/al-include.cfg"
+if ! . "/usr/lib/manjaro/common/manjaro-include.cfg" 2>/dev/null; then
+    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/manjaro-include.cfg"
     exit 1
 fi
 
@@ -42,8 +42,8 @@ else
     menuSeparator "$FAIL_MSG"
     if hash pamac-manager &>/dev/null; then
         menuItem "Install with Package Manager" "pamac-manager"
-    elif hash termite pacli &>/dev/null; then
-        menuItem "Install with Package Manager" "termite -e pacli"
+    elif hash termite pacui &>/dev/null; then
+        menuItem "Install with Package Manager" "termite -e pacui"
     fi
 fi
 menuEnd
